#!/bin/bash
FILELIST="command_classes.php
connection.class.php
cps_api.php
cps_simple.php
exception.class.php
internals/*.php
README
request.class.php
response.class.php
search_example.php
status_hmac_example.php
transactions_example.php
addtrustexternalcaroot.crt"

FOLDERNAME=php_cps_api-`date +%y%m%d`

rm -fr $FOLDERNAME
mkdir $FOLDERNAME
cp --parents -ax $FILELIST $FOLDERNAME/
tar -czvf $FOLDERNAME.tar.gz $FOLDERNAME
rm -fr $FOLDERNAME
